name = "demostack"
#account_id = "29dce13a2d4df58b57141e87fcbbc8c1"

build.command = "pnpm run build"
main = "./.cloudflare/worker.js"
site.bucket = "./.cloudflare/public"
compatibility_date = "2025-02-08"
workers_dev = false
preview_urls = false
upload_source_maps = true

routes = [
  { pattern = "demostack.lfto.me/graphql", custom_domain = true },
]

[[kv_namespaces]]
binding = "KV"
id = "c519f4d63db54b248cf5912be50e615f"

[[d1_databases]]
binding = "DB"
database_name = "demostack"
database_id = "d1ccc9b2-890a-4cdb-9f77-0bd5b678c91f"

[[queues.producers]]
queue = "demostack"
binding = "QUEUE"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "demostack_analytics"

[observability]
enabled = true
head_sampling_rate = 1