name = "demostack"
pages_build_output_dir = ".svelte-kit/cloudflare"
compatibility_date = "2025-02-08"
upload_source_maps = true

[[kv_namespaces]]
binding = "KV"
id = "c519f4d63db54b248cf5912be50e615f"

[[d1_databases]]
binding = "DB"
database_name = "demostack"
database_id = "d1ccc9b2-890a-4cdb-9f77-0bd5b678c91f"

[[durable_objects.bindings]]
class_name = "MyCounter"
name = "DO_COUNTER"
script_name = "demostack_function"

[[queues.producers]]
queue = "demostack"
binding = "QUEUE"

[[analytics_engine_datasets]]
binding = "ANALYTICS"
dataset = "demostack_analytics"