name = "demostack_function"
main = "src/index.ts"
compatibility_date = "2025-02-04"

[[migrations]]
new_classes = [ "MyCounter" ]
tag = "v1"

[[durable_objects.bindings]]
class_name = "MyCounter"
name = "DO_COUNTER"

[observability]
enabled = true
